"""editando tabela de endereco

Revision ID: 3448699bb73d
Revises: 66f403c0ec3d
Create Date: 2021-10-21 20:20:33.778513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3448699bb73d'
down_revision = '66f403c0ec3d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('number', sa.String(length=5), nullable=True))
    op.add_column('address', sa.Column('neighborhood', sa.String(length=30), nullable=True))
    op.add_column('address', sa.Column('complement', sa.String(length=100), nullable=True))
    op.add_column('address', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('address', sa.Column('state', sa.String(length=120), nullable=True))
    op.add_column('address', sa.Column('reference_point', sa.String(length=200), nullable=True))
    op.drop_column('address', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('country', sa.VARCHAR(), nullable=True))
    op.drop_column('address', 'reference_point')
    op.drop_column('address', 'state')
    op.drop_column('address', 'city')
    op.drop_column('address', 'complement')
    op.drop_column('address', 'neighborhood')
    op.drop_column('address', 'number')
    # ### end Alembic commands ###
