"""Adicionando columa quantity

Revision ID: 66f403c0ec3d
Revises: acca099a000a
Create Date: 2021-09-22 23:57:27.908200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f403c0ec3d'
down_revision = 'acca099a000a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('quantity', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'quantity')
    # ### end Alembic commands ###
